{{- if .Values.kueue.enabled }}
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: {{ .Values.kueue.localQueue.name }}
  labels:
    {{- include "karta-openshift-workload-api.labels" . | nindent 4 }}
spec:
  clusterQueue: {{ .Values.kueue.clusterQueue.name }}
{{- end }}
